### PR TITLE
ATLAS-503: Strip Out jekyll Functionality

### PR DESCRIPTION
**Pull request by nadamsoreilly**
This PR removes all the installations and files that were only used for creating standalone Jekyll sites. We no longer use that, so the atlas_assets gem has been stripped down to only be a package of assets files for use in the Atlas frontend. I also removed outdated information from the Gemspec and README files.

### CODE REVIEW

**Comment by delfanbaum** [comment]
This looks good, but before I approve, can you confirm that this now imports/works correctly in Atlas, or rather: the tests still pass?

**Review by ruralocity — APPROVED** [review]
I think this does what we need, but we'll definitely want to stage the Atlas integration prior to shipping straight to prod. (in theory we could do that prior to merging this PR, by referencing this branch or SHA in Atlas's Gemfile)

**Comment by nadamsoreilly** [comment]
The tests are passing locally for me, but I'll go ahead and push up a branch to orm-atlas to confirm that it passes the CI as well.

**Review by delfanbaum — APPROVED** [review]

**Comment by nadamsoreilly** [comment]
Everything looks normal on Staging, so I'm going to go ahead and merge

**Pull request merged**
